---
- name: Copy mx theme
  git: repo='https://github.com/okfn/ckanext-mx.git' dest=/usr/lib/ckanext-mx/

- name: Run script to change translations
  shell: /usr/lib/ckanext-mx/bin/build-combined-ckan-mo.sh