---
- name: Copy mx theme
  pip: name='git+https://github.com/mxabierto/ckanext-dgm.git#egg=ckanext-dgm' virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Run script to change translations
  shell: /usr/lib/ckan/default/src/ckanext-dgm/bin/build-combined-ckan-mo.sh