---
- name: Generate locales
  command: locale-gen {{locale}}

- name: Update locale
  command: update-locale LANGUAGE={{language}} LANG={{locale}} LC_ALL={{locale}}
  
- name: Set system locale
  shell: . /etc/default/locale

- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - nfs-kernel-server
    - nfs-common
    
- name: Create shared directory
  file: path=/mnt/disk state=directory owner=root group=root
  
- name: Create NFS exports
  copy: src=roles/nfs-server/files/exports dest=/etc/exports force=yes

- name: Restart NFS
  service: name=nfs-kernel-server state=restarted
  