---
- name: Generate locales
  command: locale-gen {{locale}}

- name: Update locale
  command: update-locale LANGUAGE={{language}} LANG={{locale}} LC_ALL={{locale}}
  
- name: Set system locale
  shell: . /etc/default/locale

- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - apache2
    - git-core
    - libapache2-mod-wsgi
    - libpq-dev
    - nginx
    - python-dev
    - python-pip
    - python-psycopg2
    - python-virtualenv

- name: Install CKAN source to virtualenv
  pip: name='git+https://github.com/ckan/ckan.git@ckan-2.2#egg=ckan' virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Install Python Requirements
  pip: requirements=/usr/lib/ckan/default/src/ckan/requirements.txt virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Create site directory
  file: path=/etc/ckan/default state=directory owner=vagrant
  
- name: Setup Development ini file
  command: /usr/lib/ckan/default/bin/paster make-config ckan /etc/ckan/default/development.ini

- name: Initialize CKAN database
  command: chdir=/etc/ckan/default /usr/lib/ckan/default/bin/paster --plugin=ckan db init

- name: Link to who.ini
  file: src=/usr/lib/ckan/default/src/ckan/who.ini dest=/etc/ckan/default/who.ini state=link force=yes

- name: Setup Production ini file
  copy: src=production.ini dest=/etc/ckan/default/production.ini

- name: Copy Apache WSGI file
  copy: src=roles/common/files/apache.wsgi dest=/etc/ckan/default/apache.wsgi force=yes

- name: Copy Apache configuration file
  copy: src=roles/common/files/ckan_default dest=/etc/apache2/sites-available/ckan_default force=yes

- name: Copy Nginx configuration file
  copy: src=roles/common/files/ckan_default_nginx dest=/etc/nginx/sites-available/ckan_default force=yes

- name: Enable CKAN site
  command: a2ensite ckan_default

- name: Enable CKAN
  file: src=/etc/nginx/sites-available/ckan_default dest=/etc/nginx/sites-enabled/ckan_default state=link force=yes 

- name: Reload Apache2
  service: name=apache2 state=reloaded
 
- name: Reload Nginx
  service: name=nginx state=reloaded

- name: Update NameVirtualPort port
  lineinfile: dest=/etc/apache2/ports.conf regexp='^NameVirtualHost' line='NameVirtualHost *:8080' backrefs=yes

- name: Update Listen port
  lineinfile: dest=/etc/apache2/ports.conf regexp='^Listen 80' line='Listen 8080' backrefs=yes

- name: Reload Apache2
  service: name=apache2 state=reloaded

- name: Reload Nginx
  service: name=nginx state=reloaded