---
- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - nfs-common
    
- name: Create mount point
  file: path=/var/lib/ckan/default state=directory
  
- name: Mount NFS directory
  mount: name=/var/lib/ckan/default src=192.168.33.30:/mnt/disk fstype=nfs state=present
  
- name: Ensure NFS directory is mounted at boot time
  lineinfile: dest=/etc/fstab
              regexp=''
              insertafter=EOF
              line='192.168.33.30:/mnt/disk   /var/lib/ckan/default   nfs   auto,noatime,nolock,bg,nfsvers=3,intr,tcp,actimeo=1800    0   0'
              state=present

- name: Reload fstab mount points
  command: mount -a

- name: Change storage ownership
  file: path=/var/lib/ckan/default state=directory owner=www-data group=www-data