---
- name: Install disqus extension
  pip: name='git+https://github.com/okfn/ckanext-disqus#egg=ckanext-disqus' virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Setting Disqus username
  ini_file: dest=/etc/ckan/default/production.ini section=app:main option=disqus.name value=YOUR_DISQUS_NAME backup=yes
