---
- hosts: dbservers
  user: vagrant
  sudo: true
  vars:
    locale: es_MX.UTF-8
    language: es_MX:es
  vars_files:
    - secrets/dbsecrets.yml
  roles:
    - postgresql-server
    - data-store
    