---
- hosts: webservers
  user: vagrant
  sudo: true
  vars:
    locale: es_MX.UTF-8
    language: es_MX:es
  vars_files:
    - secrets/dbsecrets.yml
  roles:
    - ckan-install
    - ckan-deploy
    - nfs-client
    - configuration
    - disqus-extension
    - ckanext-more-facets
